version: '3.8'

services:
  gotor-backend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: gotor-backend
    ports:
      - "8080:8080"
    volumes:
      - ./gotor-service-account.json:/etc/gotor-service-account.json
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /etc/gotor-service-account.json
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./log/nginx:/var/log/nginx

    depends_on:
      - gotor-backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge